In [ ]:
import pandas as pd

In [6]:
import pandas as pd
dict = {'Name':['Sima','Aadhya','Krishna','Radha','Vedant','Archan','Ritika','Saikat','Arindam','Purbasa','Sayak'],
        'Marks':[78,69,79,80,90,67,78,75,89,90,81],
        'Gender':['Female','Female','Male','Female','Male','Male','Female','Male','Male','Female','Male']}
df=pd.DataFrame(dict)
df

       Name  Marks  Gender
0      Sima     78  Female
1    Aadhya     69  Female
2   Krishna     79    Male
3     Radha     80  Female
4    Vedant     90    Male
5    Archan     67    Male
6    Ritika     78  Female
7    Saikat     75    Male
8   Arindam     89    Male
9   Purbasa     90  Female
10    Sayak     81    Male

Display top 3 rows of the dataset

In [5]:
df.head(3)

      Name  Marks  Gender
0     Sima     78  Female
1   Aadhya     69  Female
2  Krishna     79    Male

Display last 3 rows of the dataset

In [4]:
import pandas as pd
dict = {'Name':['Sima','Aadhya','Krishna','Radha','Vedant','Archan','Ritika','Saikat','Arindam','Purbasa','Sayak'],
        'Marks':[78,69,79,80,90,67,78,75,89,90,81],
        'Gender':['Female','Female','Male','Female','Male','Male','Female','Male','Male','Female','Male']}
df=pd.DataFrame(dict)
df

       Name  Marks  Gender
0      Sima     78  Female
1    Aadhya     69  Female
2   Krishna     79    Male
3     Radha     80  Female
4    Vedant     90    Male
5    Archan     67    Male
6    Ritika     78  Female
7    Saikat     75    Male
8   Arindam     89    Male
9   Purbasa     90  Female
10    Sayak     81    Male

In [7]:
df.head(3)

      Name  Marks  Gender
0     Sima     78  Female
1   Aadhya     69  Female
2  Krishna     79    Male

In [8]:
df.tail(3)

       Name  Marks  Gender
8   Arindam     89    Male
9   Purbasa     90  Female
10    Sayak     81    Male

3. Find Shape of our Dataset (Number of Rows & Number of Columns)

In [9]:
df.shape

(11, 3)

In [11]:
print('Number of Rows', df.shape[0])
print('Number of Columns', df.shape[1])

Number of Rows 11
Number of Columns 3

4. Get information about out Dataset like Total Number of Rows and Total Number of Columns, 
Datatypes of Each Columns and Memory

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    11 non-null     object
 1   Marks   11 non-null     int64
 2   Gender  11 non-null     object
dtypes: int64(1), object(2)
memory usage: 396.0+ bytes

5. Check Null Values in the Dataset

In [14]:
df.isnull()

     Name  Marks  Gender
0   False  False   False
1   False  False   False
2   False  False   False
3   False  False   False
4   False  False   False
5   False  False   False
6   False  False   False
7   False  False   False
8   False  False   False
9   False  False   False
10  False  False   False

In [15]:
df.isnull().sum()

Name      0
Marks     0
Gender    0
dtype: int64

6. Get overall Statistics about the Dataframe

In [18]:
df.describe()

           Marks
count  11.000000
mean   79.636364
std     7.775252
min    67.000000
25%    76.500000
50%    79.000000
75%    85.000000
max    90.000000

In [19]:
df.describe(include="all")

        Name      Marks Gender
count     11  11.000000     11
unique    11        NaN      2
top     Sima        NaN   Male
freq       1        NaN      6
mean     NaN  79.636364    NaN
std      NaN   7.775252    NaN
min      NaN  67.000000    NaN
25%      NaN  76.500000    NaN
50%      NaN  79.000000    NaN
75%      NaN  85.000000    NaN
max      NaN  90.000000    NaN

7. Find unique values from the Gender column

In [20]:
df

       Name  Marks  Gender
0      Sima     78  Female
1    Aadhya     69  Female
2   Krishna     79    Male
3     Radha     80  Female
4    Vedant     90    Male
5    Archan     67    Male
6    Ritika     78  Female
7    Saikat     75    Male
8   Arindam     89    Male
9   Purbasa     90  Female
10    Sayak     81    Male

In [21]:
df['Gender'].unique()

array(['Female', 'Male'], dtype=object)

In [22]:
df['Name'].unique()

array(['Sima', 'Aadhya', 'Krishna', 'Radha', 'Vedant', 'Archan', 'Ritika',
       'Saikat', 'Arindam', 'Purbasa', 'Sayak'], dtype=object)

In [24]:
df['Gender'].nunique()

2

In [26]:
df['Name'].nunique()

11

8. DisplayCount of Unique Values in Gender Columns

In [27]:
df['Gender'].value_counts()

Gender
Male      6
Female    5
Name: count, dtype: int64

9. Find total number of students having Marks between 90 to 100 
(Inclushive) using between Method

In [31]:
df['Marks']

0     78
1     69
2     79
3     80
4     90
5     67
6     78
7     75
8     89
9     90
10    81
Name: Marks, dtype: int64

In [34]:
df['Marks']>=90

0     False
1     False
2     False
3     False
4      True
5     False
6     False
7     False
8     False
9      True
10    False
Name: Marks, dtype: bool

In [35]:
df[df['Marks']>=90]

      Name  Marks  Gender
4   Vedant     90    Male
9  Purbasa     90  Female

In [42]:
df

       Name  Marks  Gender
0      Sima     78  Female
1    Aadhya     69  Female
2   Krishna     79    Male
3     Radha     80  Female
4    Vedant     90    Male
5    Archan     67    Male
6    Ritika     78  Female
7    Saikat     75    Male
8   Arindam     89    Male
9   Purbasa     90  Female
10    Sayak     81    Male

In [43]:
df[(df['Marks']>=90) & (df['Marks']<=100)]

      Name  Marks  Gender
4   Vedant     90    Male
9  Purbasa     90  Female

In [45]:
len(df[(df['Marks']>=90) & (df['Marks']<=100)])

2

In [46]:
# using between()
sum(df['Marks'].between(90,100))

2

10.Find average marks of the Dataset

In [47]:
df

       Name  Marks  Gender
0      Sima     78  Female
1    Aadhya     69  Female
2   Krishna     79    Male
3     Radha     80  Female
4    Vedant     90    Male
5    Archan     67    Male
6    Ritika     78  Female
7    Saikat     75    Male
8   Arindam     89    Male
9   Purbasa     90  Female
10    Sayak     81    Male

In [49]:
df['Marks'].mean()

np.float64(79.63636363636364)

In [50]:
df['Marks'].min()

67

In [51]:
df['Marks'].max()

90

11. Apply Method

In [52]:
df

       Name  Marks  Gender
0      Sima     78  Female
1    Aadhya     69  Female
2   Krishna     79    Male
3     Radha     80  Female
4    Vedant     90    Male
5    Archan     67    Male
6    Ritika     78  Female
7    Saikat     75    Male
8   Arindam     89    Male
9   Purbasa     90  Female
10    Sayak     81    Male

In [56]:
def marks(x):
    return x//2
df['Marks'].apply (marks)

0     39
1     34
2     39
3     40
4     45
5     33
6     39
7     37
8     44
9     45
10    40
Name: Marks, dtype: int64

In [57]:
df['Half_Marks']=df['Marks'].apply(marks)
df

       Name  Marks  Gender  Half_Marks
0      Sima     78  Female          39
1    Aadhya     69  Female          34
2   Krishna     79    Male          39
3     Radha     80  Female          40
4    Vedant     90    Male          45
5    Archan     67    Male          33
6    Ritika     78  Female          39
7    Saikat     75    Male          37
8   Arindam     89    Male          44
9   Purbasa     90  Female          45
10    Sayak     81    Male          40

In [58]:
# Using lambda functions..
df['Marks'].apply( lambda x:x/2)

0     39.0
1     34.5
2     39.5
3     40.0
4     45.0
5     33.5
6     39.0
7     37.5
8     44.5
9     45.0
10    40.5
Name: Marks, dtype: float64

In [60]:
df['Name'].apply(len)

0     4
1     6
2     7
3     5
4     6
5     6
6     6
7     6
8     7
9     7
10    5
Name: Name, dtype: int64

12. Map function..

In [61]:
df['Gender'].map({'Male':0,'Female':1})

0     1
1     1
2     0
3     1
4     0
5     0
6     1
7     0
8     0
9     1
10    0
Name: Gender, dtype: int64

In [63]:
df['Male_Female']= df['Gender'].map({'Male':0, 'Female':1})
df

       Name  Marks  Gender  Half_Marks  Male_Female
0      Sima     78  Female          39            1
1    Aadhya     69  Female          34            1
2   Krishna     79    Male          39            0
3     Radha     80  Female          40            1
4    Vedant     90    Male          45            0
5    Archan     67    Male          33            0
6    Ritika     78  Female          39            1
7    Saikat     75    Male          37            0
8   Arindam     89    Male          44            0
9   Purbasa     90  Female          45            1
10    Sayak     81    Male          40            0

13. Drop the column(s)

In [68]:
df.drop('Male_Female',axis=1)

       Name  Marks  Gender  Half_Marks
0      Sima     78  Female          39
1    Aadhya     69  Female          34
2   Krishna     79    Male          39
3     Radha     80  Female          40
4    Vedant     90    Male          45
5    Archan     67    Male          33
6    Ritika     78  Female          39
7    Saikat     75    Male          37
8   Arindam     89    Male          44
9   Purbasa     90  Female          45
10    Sayak     81    Male          40

In [69]:
df

       Name  Marks  Gender  Half_Marks  Male_Female
0      Sima     78  Female          39            1
1    Aadhya     69  Female          34            1
2   Krishna     79    Male          39            0
3     Radha     80  Female          40            1
4    Vedant     90    Male          45            0
5    Archan     67    Male          33            0
6    Ritika     78  Female          39            1
7    Saikat     75    Male          37            0
8   Arindam     89    Male          44            0
9   Purbasa     90  Female          45            1
10    Sayak     81    Male          40            0

14. Print Name of the columns

In [80]:
df.columns

Index(['Name', 'Marks', 'Gender'], dtype='object')

In [81]:
df.index

RangeIndex(start=0, stop=11, step=1)

15. Sort the Dataframe as per the Marks Column

In [82]:
df.sort_values(by ='Marks')

       Name  Marks  Gender
5    Archan     67    Male
1    Aadhya     69  Female
7    Saikat     75    Male
0      Sima     78  Female
6    Ritika     78  Female
2   Krishna     79    Male
3     Radha     80  Female
10    Sayak     81    Male
8   Arindam     89    Male
4    Vedant     90    Male
9   Purbasa     90  Female

In [85]:
df.sort_values(by='Marks', ascending =True)

       Name  Marks  Gender
5    Archan     67    Male
1    Aadhya     69  Female
7    Saikat     75    Male
0      Sima     78  Female
6    Ritika     78  Female
2   Krishna     79    Male
3     Radha     80  Female
10    Sayak     81    Male
8   Arindam     89    Male
4    Vedant     90    Male
9   Purbasa     90  Female

In [87]:
df.sort_values (by=['Marks', 'Gender'], ascending=True)

       Name  Marks  Gender
5    Archan     67    Male
1    Aadhya     69  Female
7    Saikat     75    Male
0      Sima     78  Female
6    Ritika     78  Female
2   Krishna     79    Male
3     Radha     80  Female
10    Sayak     81    Male
8   Arindam     89    Male
9   Purbasa     90  Female
4    Vedant     90    Male

16. Display Name and Marks of the Female students

In [88]:
df

       Name  Marks  Gender
0      Sima     78  Female
1    Aadhya     69  Female
2   Krishna     79    Male
3     Radha     80  Female
4    Vedant     90    Male
5    Archan     67    Male
6    Ritika     78  Female
7    Saikat     75    Male
8   Arindam     89    Male
9   Purbasa     90  Female
10    Sayak     81    Male

In [89]:
df['Gender']== 'Female'

0      True
1      True
2     False
3      True
4     False
5     False
6      True
7     False
8     False
9      True
10    False
Name: Gender, dtype: bool

In [90]:
df[df['Gender']== 'Female']

      Name  Marks  Gender
0     Sima     78  Female
1   Aadhya     69  Female
3    Radha     80  Female
6   Ritika     78  Female
9  Purbasa     90  Female

In [91]:
df[df['Gender']== 'Female'] ['Name']

0       Sima
1     Aadhya
3      Radha
6     Ritika
9    Purbasa
Name: Name, dtype: object

In [92]:
df[df['Gender']== 'Female'] [['Name', 'Marks']]

      Name  Marks
0     Sima     78
1   Aadhya     69
3    Radha     80
6   Ritika     78
9  Purbasa     90

In [93]:
# Using Function..
df['Gender'].isin(['Female'])

0      True
1      True
2     False
3      True
4     False
5     False
6      True
7     False
8     False
9      True
10    False
Name: Gender, dtype: bool

In [94]:
# Using Function..
df[df['Gender'].isin(['Female'])]

      Name  Marks  Gender
0     Sima     78  Female
1   Aadhya     69  Female
3    Radha     80  Female
6   Ritika     78  Female
9  Purbasa     90  Female

In [95]:
# Using Function..
df[df['Gender'].isin(['Female'])] [['Name','Marks']]

      Name  Marks
0     Sima     78
1   Aadhya     69
3    Radha     80
6   Ritika     78
9  Purbasa     90